import Link from "next/link";
import { auth } from "@/auth";
import { ArrowRight, Sparkles, Briefcase, Receipt, User, Phone } from "lucide-react";
import { Section } from "@/components/ui/section";
import { WorkspacePageHeader } from "@/components/client/page-header";
import { PrivateContact } from "@/components/client/private-contact";
import { site } from "@/config/site";

export default async function ClientOverviewPage() {
  const session = await auth();
  const name = session?.user?.name || session?.user?.email?.split("@")[0] || "there";
  const isAdmin = session?.user?.role === "admin";

  return (
    <Section className="pt-14 md:pt-16">
      <WorkspacePageHeader
        eyebrow="Workspace · Overview"
        title={`Welcome, ${name}.`}
        description="This is your private workspace with Gautam. Everything you need to explore engagement options, analyse your project, or reach out directly."
      />

      {isAdmin && (
        <div className="mt-8 rounded-xl border border-gold/40 bg-gold/5 p-4 md:p-5">
          <p className="font-mono text-[10px] uppercase tracking-widest text-gold">Administrator</p>
          <p className="mt-1 text-sm text-ink">
            You have admin access. The Admin panel is available from the workspace nav.
          </p>
        </div>
      )}

      {/* Feature grid */}
      <div className="mt-12 grid gap-6 md:grid-cols-6">
        {/* Project Intelligence — hero card */}
        <Link
          href="/client/intelligence"
          className="group relative col-span-1 flex flex-col overflow-hidden rounded-xl border border-gold/40 bg-elevated/70 p-8 transition-all hover:-translate-y-0.5 hover:border-gold/70 md:col-span-4"
        >
          <div className="absolute inset-0 bg-radial-glow opacity-40" aria-hidden />
          <div className="corner-brackets absolute inset-4" aria-hidden />
          <div className="relative flex items-start justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-md border border-gold/40 bg-gold/10 text-gold">
                <Sparkles className="h-5 w-5" />
              </div>
              <div>
                <p className="font-mono text-[10px] uppercase tracking-widest text-gold">Featured</p>
                <h2 className="mt-1 font-display text-2xl font-medium text-ink md:text-3xl">Project Intelligence</h2>
              </div>
            </div>
            <ArrowRight className="h-5 w-5 text-ink-muted transition-all group-hover:-translate-y-0.5 group-hover:translate-x-1 group-hover:text-gold" />
          </div>
          <p className="relative mt-8 max-w-xl text-ink-muted text-pretty">
            Describe your project idea. Get an architectural breakdown, complexity read, suggested technology stack and next step —
            generated by a Gemini-powered analysis engine.
          </p>
          <div className="relative mt-10 flex flex-wrap gap-2">
            {["Architecture read", "AI layer suggestion", "Tech stack", "Complexity signal", "Next step"].map((tag) => (
              <span key={tag} className="rounded-full border border-hairline/25 bg-elevated/40 px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-ink-muted">
                {tag}
              </span>
            ))}
          </div>
        </Link>

        {/* Direct contact — split card */}
        <div className="relative col-span-1 flex flex-col overflow-hidden rounded-xl border border-hairline/25 bg-elevated/50 p-8 md:col-span-2">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-md border border-hairline/25 bg-base/50 text-ink">
              <Phone className="h-5 w-5" />
            </div>
            <h2 className="font-display text-xl font-medium text-ink">Direct Contact</h2>
          </div>
          <p className="mt-4 text-sm text-ink-muted text-pretty">
            Reveal Gautam&apos;s private phone number. Available only to authenticated clients.
          </p>
          <div className="mt-auto pt-6">
            <PrivateContact />
          </div>
        </div>
      </div>

      {/* Secondary grid */}
      <div className="mt-6 grid gap-6 md:grid-cols-3">
        <NavCard
          href="/client/services"
          icon={<Briefcase className="h-5 w-5" />}
          title="Services"
          description="Detailed capabilities across full-stack, AI, cloud, automation and e-commerce."
        />
        <NavCard
          href="/client/pricing"
          icon={<Receipt className="h-5 w-5" />}
          title="Pricing & Engagements"
          description="How engagements are scoped, priced and delivered. Starting-from tiers and custom quotes."
        />
        <NavCard
          href="/client/about"
          icon={<User className="h-5 w-5" />}
          title="About Gautam"
          description="Background, focus areas and the way work actually happens."
        />
      </div>

      {/* Footer strip */}
      <div className="mt-16 flex flex-col items-start justify-between gap-4 rounded-xl border border-hairline/20 bg-elevated/30 p-6 md:flex-row md:items-center md:p-8">
        <p className="text-sm text-ink-muted text-pretty">
          Ready to formalise a project? Send a project brief through the intake form.
        </p>
        <Link
          href="/start-a-project"
          className="inline-flex items-center gap-2 rounded-md border border-gold/50 bg-gold/10 px-5 py-2.5 text-sm text-gold transition-colors hover:bg-gold/15"
        >
          Send a project brief <ArrowRight className="h-4 w-4" />
        </Link>
      </div>

      <div className="mt-12 text-center font-mono text-[10px] uppercase tracking-widest text-ink-subtle">
        Private workspace · {site.brand}
      </div>
    </Section>
  );
}

function NavCard({
  href,
  icon,
  title,
  description,
}: {
  href: string;
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <Link
      href={href}
      className="group relative flex flex-col rounded-xl border border-hairline/25 bg-elevated/40 p-7 transition-all hover:-translate-y-0.5 hover:border-gold/40 hover:bg-elevated/70"
    >
      <div className="flex items-center gap-3">
        <div className="flex h-9 w-9 items-center justify-center rounded-md border border-hairline/25 bg-base/60 text-ink-muted transition-colors group-hover:border-gold/40 group-hover:text-gold">
          {icon}
        </div>
        <h3 className="font-display text-lg font-medium text-ink">{title}</h3>
      </div>
      <p className="mt-4 text-sm text-ink-muted text-pretty">{description}</p>
      <div className="mt-5 inline-flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-widest text-ink-muted group-hover:text-gold">
        Open <ArrowRight className="h-3 w-3 transition-transform group-hover:translate-x-0.5" />
      </div>
    </Link>
  );
}
